"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PageButton = exports.PaginationContainer = exports.ArchiveButton = exports.PublishButton = exports.Table = exports.TabNav = exports.TableContainer = exports.ReviewSection = exports.SectionTitle = exports.Container = void 0;
var styled_components_1 = require("styled-components");
exports.Container = styled_components_1.styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  padding: 5%;\n  background-color: #f7f7f7;\n  min-height: 100vh;\n  display: flex;\n  flex-direction: column;\n  color: #333;\n"], ["\n  padding: 5%;\n  background-color: #f7f7f7;\n  min-height: 100vh;\n  display: flex;\n  flex-direction: column;\n  color: #333;\n"])));
exports.SectionTitle = styled_components_1.styled.h2(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  font-size: 1.5rem;\n  color: #333;\n  margin-bottom: 2rem;\n"], ["\n  font-size: 1.5rem;\n  color: #333;\n  margin-bottom: 2rem;\n"])));
exports.ReviewSection = styled_components_1.styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  background-color: white;\n  padding: 5%;\n  border-radius: 0.75em;\n  box-shadow: 0 0.25em 0.375em rgba(0, 0, 0, 0.1);\n  margin-bottom: 2rem;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  flex-wrap: wrap;\n"], ["\n  background-color: white;\n  padding: 5%;\n  border-radius: 0.75em;\n  box-shadow: 0 0.25em 0.375em rgba(0, 0, 0, 0.1);\n  margin-bottom: 2rem;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  flex-wrap: wrap;\n"])));
exports.TableContainer = styled_components_1.styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  background-color: white;\n  padding: 2%;\n  border-radius: 0.75em;\n  box-shadow: 0 0.25em 0.375em rgba(0, 0, 0, 0.1);\n  flex-grow: 1;\n"], ["\n  background-color: white;\n  padding: 2%;\n  border-radius: 0.75em;\n  box-shadow: 0 0.25em 0.375em rgba(0, 0, 0, 0.1);\n  flex-grow: 1;\n"])));
exports.TabNav = styled_components_1.styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  display: flex;\n  border-bottom: 0.1em solid #ddd;\n  margin-bottom: 2rem;\n\n  button {\n    padding: 1% 2%;\n    background: none;\n    border: none;\n    border-bottom: 0.2em solid transparent;\n    cursor: pointer;\n    font-weight: bold;\n    color: #333;\n\n    &:hover,\n    &.active {\n      border-bottom: 0.2em solid #135846;\n      color: #135846;\n    }\n  }\n"], ["\n  display: flex;\n  border-bottom: 0.1em solid #ddd;\n  margin-bottom: 2rem;\n\n  button {\n    padding: 1% 2%;\n    background: none;\n    border: none;\n    border-bottom: 0.2em solid transparent;\n    cursor: pointer;\n    font-weight: bold;\n    color: #333;\n\n    &:hover,\n    &.active {\n      border-bottom: 0.2em solid #135846;\n      color: #135846;\n    }\n  }\n"])));
exports.Table = styled_components_1.styled.table(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  width: 100%;\n  border-collapse: collapse;\n\n  th,\n  td {\n    padding: 1.5%;\n    border-bottom: 0.1em solid #ddd;\n    text-align: left;\n    font-size: 1rem;\n  }\n"], ["\n  width: 100%;\n  border-collapse: collapse;\n\n  th,\n  td {\n    padding: 1.5%;\n    border-bottom: 0.1em solid #ddd;\n    text-align: left;\n    font-size: 1rem;\n  }\n"])));
exports.PublishButton = styled_components_1.styled.button(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  background: none;\n  border: none;\n  color: #28a745;\n  cursor: pointer;\n\n  &:hover {\n    color: #218838;\n  }\n"], ["\n  background: none;\n  border: none;\n  color: #28a745;\n  cursor: pointer;\n\n  &:hover {\n    color: #218838;\n  }\n"])));
exports.ArchiveButton = styled_components_1.styled.button(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  background: none;\n  border: none;\n  color: #dc3545;\n  cursor: pointer;\n\n  &:hover {\n    color: #c82333;\n  }\n"], ["\n  background: none;\n  border: none;\n  color: #dc3545;\n  cursor: pointer;\n\n  &:hover {\n    color: #c82333;\n  }\n"])));
exports.PaginationContainer = styled_components_1.styled.div(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  display: flex;\n  justify-content: center;\n  margin-top: 1rem;\n"], ["\n  display: flex;\n  justify-content: center;\n  margin-top: 1rem;\n"])));
exports.PageButton = styled_components_1.styled.button(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  padding: 0.5rem 1rem;\n  margin: 0 0.5rem;\n  background-color: ", ";\n  color: ", ";\n  border: 1px solid #ddd;\n  cursor: pointer;\n  border-radius: 5px;\n\n  &:hover {\n    background-color: #135846;\n    color: white;\n  }\n"], ["\n  padding: 0.5rem 1rem;\n  margin: 0 0.5rem;\n  background-color: ", ";\n  color: ", ";\n  border: 1px solid #ddd;\n  cursor: pointer;\n  border-radius: 5px;\n\n  &:hover {\n    background-color: #135846;\n    color: white;\n  }\n"])), function (_a) {
    var $active = _a.$active;
    return ($active ? '#135846' : 'white');
}, function (_a) {
    var $active = _a.$active;
    return ($active ? 'white' : '#333');
});
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10;
